export const BUILDSHEET_TEXT = {
  companyName: "湖南华通众智科技有限公司",
  quoteInfoRows: [
    ["客户名称:", "", "", ""],
    ["联系人:", "", "客户电话:", ""],
    ["交货地点:", "", "客户传真:", ""],
    ["交货时间:", "", "REF. No.", ""],
    ["付款方式:", "", "客户E-MAIL:", ""],
    ["工程名称:", "", "项目编号:", ""],
  ] as string[][],
  quoteTitle: "配置报价表",
  quoteHeader: ["序号", "项目", "单价（元）", "备注"] as string[],
  quoteDefaultItems: [
    [1, "原料给料系统", "", ""],
    [2, "改性剂给料系统", "", ""],
    [3, "磨机系统", "", ""],
    [4, "除尘器系统", "", ""],
    [5, "加热系统", "", ""],
    [6, "输送管道部分", "", ""],
    [7, "仪器仪表", "", ""],
    [8, "公用工程", "", ""],
    [9, "钢构", "", ""],
    [10, "控制系统部分", "", ""],
    [11, "筛分除磁包装", "", ""],
    [12, "包装、运输", "", ""],
    [13, "安装、调试", "", ""],
  ] as Array<[number, string, string, string]>,
  totalLabel: "总计（万元）",
  remarkLabel: "备注",
  quoteNotes: [
    "1) 以上报价不含电缆和桥架，不含筒体料仓、水气管路（由客户提供），不含管道保温。",
    "2) 华通负责现场安装、调试，不含设备操作钢架平台；供货范围以施工图为准，其它由客户按图制作。",
    "3) 以上报价含13%增值税，含现场安装调试费用，含运保费。",
    "4) 本报价包含软件费用，签订建设合同时需分项注明。",
    "5) 以上报价不含涉及土建、建筑改动、拆墙、穿墙洞、打楼板等费用。",
    "6) 业主需配备机电操作维护人员，方可保证设备高效运行。",
    "7) 安装调试期间，操作维修及现场主管人员需参与培训，并设对口负责人。",
  ] as string[],
  configHeaders: [
    "系列",
    "设备名称",
    "组件名称",
    "内容及规格",
    "型号",
    "材质",
    "品牌",
    "组件数量",
    "单位",
    "数量",
    "单位",
    "单价（万元）",
    "总价（万元）",
    "成本单价（元）",
    "成本合计（元）",
    "合计（元）",
    "系数",
    "备注",
    "备注",
  ] as string[],
  configSections: [
    "一、原料给料系统",
    "二、改性剂给料系统",
    "三、磨机系统",
    "四、除尘器系统",
    "五、加热系统",
    "六、输送管道部分",
    "七、仪器仪表",
    "八、公用工程",
    "九、钢构",
    "十、控制系统部分",
    "十一、筛分除磁包装",
    "十二、包装、运输",
    "十三、安装、调试",
  ] as string[],
  configSectionTotalLabel: "总价",
  wearPartsTitle: "易损件表",
  wearPartsHeaders: [
    "序号",
    "设备名称",
    "规格",
    "型号",
    "材质",
    "品牌",
    "数量",
    "单位",
    "单价（万元）",
    "总价（万元）",
    "成本单价（元）",
    "成本总价（元）",
    "系数",
    "备注",
    "备注",
  ] as string[],
} as const;

export const BUSINESS_TERMS = {
  setUnit: "套",
} as const;

export const SECTION_TITLE_PREFIX_REGEX = /^((一|二|三|四|五|六|七|八|九|十|十一|十二|十三|十四|十五|十六|十七|十八|十九|二十)|(\d{1,3}))[、.．]/;

export const FLOW_MESSAGES = {
  dialogParseFailed: "解析对话框返回数据失败",
  openDevDialogFailed: "打开更改设备窗口失败",
  openCraftDialogFailed: "打开工艺更改窗口失败",
  outsourcedPriceNotSelected: "外购件未选择价格，跳过更新",
  componentNotFoundPrefix: "未找到对应组件配置",
  openQueryPriceFailed: "打开查询价格失败",
  openQueryPriceDialogFailed: "打开查询对话框失败",
  validateFailedPrefix: "验证失败",
  worksheetNotFoundPrefix: "工作表不存在",
  selectionInvalidPrefix: "请在指定工作表中操作。当前位置：",
  missingRequiredSelection: "当前行缺少分类/型号/组件名称，无法继续",
  selectionReadFailed: "读取当前选区失败",
  requestFailed: "请求失败",
  projectModelNotFoundPrefix: "未找到项目型号",
  missingCategoryOrProject: "缺少必要的产品类型或产品型号信息",
  noDetailSelected: "没有选择任何组件",
  fetchConfigFailedPrefix: "获取组件数据失败",
  fetchDetailFailed: "获取组件详情失败",
  dbConnectionFailedPrefix: "无法连接到数据库服务器",
  querySystemMapping: "查询产品类型对应系统",
  foundSystemMapping: "找到系统映射",
  notFoundSystemMapping: "未找到系统映射",
  querySystemMappingFailed: "查询系统映射失败",
  selectQuoteConfigColumnsPrefix: "请先选中报价配置表 C/D/E/F 列的组件单元格",
  quoteConfigOnlyCColumnPrefix: "需要先选中C列【组件名称】的某个单元格",
  preparingInsert: "准备插入数据",
  quoteConfigMissingPrefix: "报价配置表不存在，请先创建报价配置表",
  insertConfigFailedPrefix: "插入数据到报价配置表失败",
  sectionTitleNotFoundPrefix: "未找到分区标题",
  replaceOnHeaderOrSectionForbidden: "当前选中分区标题行/表头行，不允许替换",
} as const;

export const DIALOG_TEXT = {
  ready: "Dialog 已就绪",
  selectProjectPlaceholder: "→ 选择项目后显示图片",
  selectProductPlaceholder: "→ 选择产品后显示图片",
  loading: "加载中...",
  loadCategoryFailed: "加载产品类型失败",
  loadProjectFailed: "加载产品型号失败",
  loadFailed: "加载失败",
  loadComponentFailed: "加载组件失败",
  loadAccessoryFailed: "加载配件失败",
  loadProjectDetailFailed: "加载项目详情失败",
  loadDetailsFailed: "Details 加载失败",
  loadAnnotationsFailed: "Annotations 加载失败",
  noCategoryData: "暂无产品类型",
  noProjectData: "该类型下暂无产品",
  noDetailData: "暂无组件信息",
  noAnnotationData: "暂无可选配件",
  unknownError: "未知错误",
  dbConnectFailed: "无法连接到数据库服务器",
  requiredSuffix: " [必选]",
  componentImageLoadFailed: "组件图片加载失败",
  canvasNotFound: "Canvas element not found",
  canvasRendered: "Canvas 渲染完成，组件数量",
  tooltipPrefix: "组件: ",
  imageLoadFailed: "图片加载失败",
  noProductImage: "暂无产品图片",
  selectedAnnotations: "当前选中的可选配件",
  needSelectCategoryAndProject: "请先选择产品类型和产品型号",
  needSelectAtLeastOneDetail: "请至少选择一个组件",
  exportedCompositeImage: "已导出合成图片，大小",
  exportCompositeImageFailed: "导出合成图片失败",
  submitData: "提交数据",
  summaryCategory: "产品类型",
  summaryProject: "产品型号",
  summarySelectedDetailCount: "选中组件",
  summarySelectedAnnotationCount: "可选配件",
  summaryHasCompositeImage: "包含合成图片",
  countSuffix: " 个",
  queryFailed: "查询失败",
  handleParentMessageFailed: "处理父窗口消息失败",
  brandKeywords: ["品牌/制造商", "品牌", "制造商"] as string[],
  materialKeywords: ["材质"] as string[],
} as const;

export const DEVMODIFY_TEXT = {
  initDataHandleFailed: "处理初始化数据失败",
  registerParentMessageFailed: "未能注册父窗口消息处理",
  selectPlaceholder: "请选择...",
  clickToQuery: "点击查询",
  clickToModify: "点击更改",
  outsourcedPriceLabel: "外购价格",
  craftProcessLabel: "表面处理",
  priceSearchFailed: "价格查询失败",
  priceTableHeaderHtml: "<div>物料名称</div><div>规格描述</div><div>型号</div><div>价格</div>",
  brandKeywords: ["品牌/制造商", "品牌", "制造商"] as string[],
  materialKeywords: ["材质"] as string[],
} as const;

export const CRAFTMODIFY_TEXT = {
  initDataHandleFailed: "处理初始化数据失败",
  registerParentMessageFailed: "未能注册父窗口消息处理",
  selectPlaceholder: "请选择...",
  innerPrefix: "，内表面处理：",
  outerPrefix: "，外表面处理：",
  innerLabel: "内表面处理：",
  outerLabel: "外表面处理：",
  semicolon: "；",
  comma: "，",
} as const;

export const DIALOG_HTML_TEXT = {
  title: "数据输入对话框",
  categoryTitle: "产品类型",
  projectTitle: "产品型号",
  detailTitle: "详细信息（多选）",
  annotationTitle: "标注选项（多选）",
  previewTitle: "图片预览与标注",
  clearAll: "清除全部",
  confirmSubmit: "确认提交",
} as const;

export const QUERYPRICE_HTML_TEXT = {
  title: "查询价格",
  colName: "物料名称",
  colDesc: "规格描述",
  colType: "型号",
  colPrice: "价格",
  labelMainKeyword: "物料名称",
  labelSecondKeyword: "关键词",
  phMainKeyword: "输入物料名称...",
  phSecondKeyword: "输入关键词（可选）...",
  btnCancel: "取消",
  btnSearch: "查询",
  btnReplace: "替换数据",
  warningTitle: "提示",
  btnOk: "确定",
} as const;

