$ErrorActionPreference = 'Stop'

$sourcePath = 'C:\Users\zhuhuihua\Desktop\欧米亚 DCM1500-FJ 包覆改性系统项目_20260205-V01.xlsx'
$outputPath = 'C:\Users\zhuhuihua\Desktop\OMYA DCM1500-FJ Coating Modification System Project_20260205-V01_EN.xlsx'

$sheetNameMap = @{
  'ASD750预干和DCM1500改性系统报价' = 'ASD750 & DCM1500 Quote'
  '配置表' = 'Configuration'
}

$translations = @{
  '∮125*2500mm Q235 有机硅涂层' = '∮125*2500mm Q235 with organosilicone coating'
  '1、改性剂(硬脂酸)颗粒真空上料系统' = '1. Modifier (stearic acid) granule vacuum conveying system'
  '1、进料装置' = '1. Feeding device'
  '1、脉冲布袋除尘器(离线式)及系统风机' = '1. Pulse bag dust collector (offline type) and system fan'
  '1、脉冲布袋除尘器及系统风机' = '1. Pulse bag dust collector and system fan'
  '1、系统管道部分，每套含以下内容' = '1. System piping section, each set includes the following'
  '1、原料失重给料机（精度：±1%), 包含以下内容：' = '1. Raw material loss-in-weight feeder (accuracy: ±1%), including the following:'
  '1、ASD主机，包含以下内容：' = '1. ASD main unit, including the following:'
  '1、DCM1500主机，包含以下内容：' = '1. DCM1500 main unit, including the following:'
  '2、分级机，包含以下内容：' = '2. Classifier, including the following:'
  '2、改性剂进料部分(精度：0.5%），包含以下内容：' = '2. Modifier feeding section (accuracy: 0.5%), including the following:'
  '2、旋转阀' = '2. Rotary valve'
  '2、ASD600仪器仪表 每套包括以下内容：' = '2. ASD600 instrumentation, each set includes the following:'
  '2、DCM1500仪器仪表 每套包括以下内容：' = '2. DCM1500 instrumentation, each set includes the following:'
  '3、改性剂管道部分，包含以下内容：' = '3. Modifier piping section, including the following:'
  '3、其余阀门' = '3. Remaining valves'
  '4、溜管、软连接、其他附件' = '4. Chutes, flexible connectors, and other accessories'
  '45#钢结构+高碳耐磨叶片' = '45# steel structure + high-carbon wear-resistant blades'
  '45#喷漆' = '45# painted finish'
  '7袋' = '7 bags'
  '安装调试期间,操作维修人员必须参与教育训练,参与人员为操作、维修、现场主管,并设对口负责人员。' = 'During installation and commissioning, operations and maintenance personnel must participate in training, including operators, maintenance staff, and site supervisors, with designated responsible counterparts.'
  '八、改性原料给料系统' = 'VIII. Modified material feeding system'
  '包括过滤器，阀门等' = 'Including filters, valves, etc.'
  '报价日期：2026年01月30日' = 'Quotation Date: January 30, 2026'
  '报价日期：2026年02月05日' = 'Quotation Date: February 05, 2026'
  '备' = 'Remarks'
  '注：' = ':'
  "备`n注：" = 'Remarks:'
  '本报价包括20%软件费用，签订建设合同时需分项注明此费用；' = 'This quotation includes a 20% software fee, which must be itemized when signing the construction contract;'
  '玻璃钢' = 'FRP'
  '博能或国内同等品牌' = 'Boneng or equivalent domestic brand'
  '布袋' = 'Filter bags'
  '布袋龙骨架' = 'Bag cage'
  '布袋收尘尾气管道' = 'Bag filter exhaust duct'
  '材质' = 'Material'
  '材质：碳钢表，外保温100mm' = 'Material: carbon steel exterior, with 100 mm external insulation'
  '材质：碳钢表面喷漆' = 'Material: painted carbon steel surface'
  '称重传感器' = 'Load cell'
  '齿圈材质：40Cr' = 'Ring gear material: 40Cr'
  '出料口：DN50 气动开关阀可与改性剂失重秤连接' = 'Outlet: DN50 pneumatic shut-off valve connectable to the modifier loss-in-weight scale'
  '出料螺旋' = 'Discharge screw'
  '触摸屏' = 'Touchscreen'
  '垂直搅拌减速电机，定频电机' = 'Vertical stirring geared motor, fixed-frequency motor'
  '单价' = 'Unit Price'
  '单位' = 'Unit'
  '低压电气柜' = 'Low-voltage electrical cabinet'
  '电机型号：160KW，IE4,IP55，变频电机，变频控制' = 'Motor model: 160KW, IE4, IP55, variable-frequency motor, VFD control'
  '电机型号：22KW，IE4,IP55，变频电机，变频控制' = 'Motor model: 22KW, IE4, IP55, variable-frequency motor, VFD control'
  '电机型号：37KW，IE4,IP55，变频电机，变频控制' = 'Motor model: 37KW, IE4, IP55, variable-frequency motor, VFD control'
  '电加热熔炼桶' = 'Electrically heated melting tank'
  '电缆' = 'Cable'
  '电缆桥架和附件' = 'Cable trays and accessories'
  '碟片夹板' = 'Disc clamping plate'
  '碟片夹板：Q235 表面喷漆' = 'Disc clamping plate: Q235, painted surface'
  '碟片盘轴套' = 'Disc shaft sleeve'
  '定频电机、变频控制,1.1kw' = 'Fixed-frequency motor, VFD control, 1.1 kW'
  '定频电机、变频控制，1.1kw' = 'Fixed-frequency motor, VFD control, 1.1 kW'
  '动力柜至控制柜电缆' = 'Cable from power cabinet to control cabinet'
  '吨包和小包兼容拆包站，S304' = 'Unpacking station compatible with jumbo bags and small bags, S304'
  '多叶片转子' = 'Multi-vane rotor'
  '二、ASD750 干燥系统' = 'II. ASD750 drying system'
  '分级机变频器' = 'Classifier VFD'
  '分级机电机' = 'Classifier motor'
  '分级轮' = 'Classifying wheel'
  '分散盘' = 'Dispersion disc'
  '风机变频器' = 'Fan VFD'
  '锋杰或同等品牌' = 'Fengjie or equivalent brand'
  '付款方式（Payment）：30%+55%+10%+5%' = 'Payment Terms: 30% + 55% + 10% + 5%'
  '负压风机' = 'Negative-pressure fan'
  '改性机出料直管' = 'Modification machine discharge straight pipe'
  '改性机进料管' = 'Modification machine feed pipe'
  '改性剂出料直管' = 'Modifier discharge straight pipe'
  '改性剂进料管' = 'Modifier feed pipe'
  '钢构大平台和甲供设备支撑由需方负责' = 'Large steel platform and supports for owner-supplied equipment shall be provided by the buyer'
  '钢平台' = 'Steel platform'
  '钢丝软管' = 'Steel wire hose'
  '高温泵，流量：15~100kg/h；无脉冲齿轮泵' = 'High-temperature pump, flow rate: 15-100 kg/h; non-pulsating gear pump'
  '高压涡旋风机 7.5KW' = 'High-pressure vortex fan 7.5KW'
  '个' = 'pc'
  '给料泵' = 'Feed pump'
  '工程名称（Project）：DCM1500FJ碟巢磨改性系统' = 'Project: DCM1500FJ disc-nest mill modification system'
  '功率：110kw；风量：约20000m³/h，全压：约11000Pa，变频控制，过流面材质：碳钢（含减震垫）' = 'Power: 110 kW; air volume: approx. 20,000 m3/h; total pressure: approx. 11,000 Pa; VFD control; wetted surface material: carbon steel (including vibration damping pad)'
  '功率：30kw； 风量：4000m³/变频控制，过流面材质：碳钢（含减震垫）' = 'Power: 30 kW; air volume: 4,000 m3/h; VFD control; wetted surface material: carbon steel (including vibration damping pad)'
  '管道' = 'Piping'
  '管道保温' = 'Pipe insulation'
  '管道保温带，做保温棉防护' = 'Pipe insulation wrap with insulation cotton protection'
  '管道用' = 'For piping'
  '管路温度使用' = 'For pipeline temperature service'
  '规格型号：DN20' = 'Specification/model: DN20'
  '规格型号：DN500，材质：Q235 内表面喷防锈底漆，外表面喷底漆+面漆' = 'Specification/model: DN500, material: Q235, inner surface with anti-rust primer, outer surface with primer + topcoat'
  '硅胶' = 'Silicone'
  '国优' = 'National premium brand'
  '含控制模块、西门子PLC' = 'Including control module and Siemens PLC'
  '虹润' = 'Hongrun'
  '湖南华通' = 'Hunan Huatong'
  '湖南华通众智科技有限公司' = 'Hunan Huatong Zhongzhi Technology Co., Ltd.'
  '华通定制' = 'Customized by Huatong'
  '华通负责现场指导安装、调试，不含任何设备和操作钢架平台，供货由原料失重秤进料闸阀开始至收尘器出料旋转阀为止，其它可由买方根据华通设计施工图进行制作' = 'Huatong is responsible for on-site installation guidance and commissioning, excluding any equipment and operating steel platforms. The supply scope starts from the inlet gate valve of the raw material loss-in-weight scale and ends at the discharge rotary valve of the dust collector. Other parts may be fabricated by the buyer according to Huatong design drawings.'
  '华通仅提供动力柜之后部分，玻璃钢桥架' = 'Huatong only provides the section downstream of the power cabinet, with FRP cable tray'
  '汇川' = 'Inovance'
  '机座及外壳' = 'Base and housing'
  '加热带' = 'Heating belt'
  '加速室' = 'Acceleration chamber'
  '减速电机' = 'Geared motor'
  '交货地点（Place of Delivery)：' = 'Place of Delivery:'
  '交货时间（Time of Delivery)：' = 'Time of Delivery:'
  '结构件' = 'Structural parts'
  '解包站' = 'Unpacking station'
  '进出口' = 'Inlet and outlet'
  '进料雾化器' = 'Feed atomizer'
  '九、改性剂给料系统' = 'IX. Modifier feeding system'
  '柯力' = 'Keli'
  '柯力传感器' = 'Keli sensor'
  '客户传真：' = 'Customer Fax:'
  '客户电话:' = 'Customer Phone:'
  '客户名称（Messers）： OMYA' = 'Customer Name (Messers): OMYA'
  '客户提供' = 'Provided by customer'
  '客户E-MAIL：' = 'Customer E-MAIL:'
  '空气流量计' = 'Air flowmeter'
  '控制柜至各设备电缆' = 'Cables from control cabinet to each equipment item'
  '控制器' = 'Controller'
  '类型：在线式，过滤面积：110㎡，主箱体材质：Q235，内表面喷涂打磨除渣，外面喷涂防锈底漆+面漆' = 'Type: online, filtration area: 110 m2, main casing material: Q235, inner surface polished and deslagged with coating, outer surface coated with anti-rust primer + topcoat'
  '类型：在线式，过滤面积：560㎡，主箱体材质：Q235，内表面喷涂打磨除渣，外面喷涂防锈底漆+面漆，外保温50mm,保温外壳为碳钢' = 'Type: online, filtration area: 560 m2, main casing material: Q235, inner surface polished and deslagged with coating, outer surface coated with anti-rust primer + topcoat, external insulation 50 mm, insulation cladding in carbon steel'
  '联系人（Attn.)：耿总' = 'Attn.: Mr. Geng'
  '料仓' = 'Silo'
  '料仓简易支撑钢架' = 'Simple support steel frame for silo'
  '溜管' = 'Chute'
  '六、钢平台及设备支撑' = 'VI. Steel platform and equipment supports'
  '罗茨风机' = 'Roots blower'
  '螺旋输送减速电机，变频电机' = 'Screw conveying geared motor, variable-frequency motor'
  '买方传真：' = 'Buyer Fax:'
  '买方电话:' = 'Buyer Phone:'
  '买方订购回签：' = 'Buyer Purchase Confirmation Signature:'
  '买方负责' = 'Responsible by buyer'
  '买方名称（Messers）： OMYA' = 'Buyer Name (Messers): OMYA'
  '买方提供' = 'Provided by buyer'
  '买方E-MAIL：' = 'Buyer E-MAIL:'
  '麦克' = 'Maike'
  '脉冲布袋除尘器' = 'Pulse bag dust collector'
  '脉冲阀' = 'Pulse valve'
  '脉冲控制仪' = 'Pulse controller'
  '梅特勒或威世' = 'Mettler or VPG'
  '梅特勒托利多C3传感器' = 'Mettler Toledo C3 sensor'
  '米' = 'm'
  '耐磨齿圈' = 'Wear-resistant ring gear'
  '耐温150℃，防静电，外表面覆膜聚四氟乙烯膜' = 'Temperature resistant to 150C, antistatic, outer surface laminated with PTFE film'
  '南京法派' = 'Nanjing Fapai'
  '南京能兆' = 'Nanjing Nengzhao'
  '内部零件耗材' = 'Internal parts consumables'
  '配件' = 'Accessories'
  '配置垂直搅拌' = 'Configured with vertical stirring'
  '配置水平搅拌+螺旋输送' = 'Configured with horizontal stirring + screw conveying'
  '品牌' = 'Brand'
  '七、预干燥控制系统部分,' = 'VII. Pre-drying control system,'
  '气锤(4只)，电磁阀，气管及接头等一批' = 'Air hammers (4 pcs), solenoid valves, air pipes, fittings, etc.'
  '气动蝶阀' = 'Pneumatic butterfly valve'
  '气动清壁装置' = 'Pneumatic wall-cleaning device'
  '气动闸阀' = 'Pneumatic gate valve'
  '全容积：1500L' = 'Total volume: 1500L'
  '全容积：200L' = 'Total volume: 200L'
  '全容积：50L' = 'Total volume: 50L'
  '燃炉腔' = 'Furnace chamber'
  '燃烧器' = 'Burner'
  '热风进气管' = 'Hot air inlet pipe'
  '软连接' = 'Flexible connector'
  '三、预干燥除尘系统' = 'III. Pre-drying dust collection system'
  '设备名称规格' = 'Equipment Name / Specification'
  '失重秤体' = 'Loss-in-weight scale body'
  '失重控制系统' = 'Loss-in-weight control system'
  '失重料仓' = 'Loss-in-weight hopper'
  '十、DCM1500FJ 改性系统' = 'X. DCM1500FJ modification system'
  '十二、改性天然气直燃热风炉' = 'XII. Natural gas direct-fired hot air furnace for modification'
  '十六、运费、安装调试费用，每套含以下内容：' = 'XVI. Freight, installation and commissioning fees, each set includes the following:'
  '十三、改性管道、仪表部分' = 'XIII. Modification piping and instrumentation section'
  '十四、钢平台及设备支撑以及管道保温' = 'XIV. Steel platform, equipment supports, and pipe insulation'
  '十五、改性控制系统部分' = 'XV. Modification control system section'
  '十一、改性除尘系统' = 'XI. Modification dust collection system'
  '输送管道' = 'Conveying pipeline'
  '输送弯头' = 'Conveying elbow'
  '数量' = 'Qty'
  '水平搅拌减速电机，定频电机' = 'Horizontal stirring geared motor, fixed-frequency motor'
  '四、预干燥天然气直燃热风炉' = 'IV. Pre-drying natural gas direct-fired hot air furnace'
  '苏州协昌' = 'Suzhou Xiechang'
  '台' = 'set'
  '碳钢' = 'Carbon steel'
  '碳钢材质' = 'Carbon steel material'
  '碳钢防腐' = 'Corrosion-protected carbon steel'
  '碳钢喷塑' = 'Powder-coated carbon steel'
  '套' = 'set'
  '体积喂料机' = 'Volumetric feeder'
  '皖南或国内同等品牌' = 'Wannan or equivalent domestic brand'
  '温度变送器' = 'Temperature transmitter'
  '五、管道、仪表部分' = 'V. Piping and instrumentation section'
  '雾化器' = 'Atomizer'
  '西门子PLCS7-1200；精度控制：0.5%' = 'Siemens PLC S7-1200; accuracy control: 0.5%'
  '系统风机' = 'System fan'
  '系统风量' = 'System air volume'
  '线性燃烧器，大小火调节，40万大卡' = 'Linear burner, high/low fire adjustment, 400,000 kcal'
  '项目编号：' = 'Project No.:'
  '橡胶' = 'Rubber'
  '橡胶软接' = 'Rubber flexible joint'
  '卸货、转移、吊装、指导安装、调试' = 'Unloading, transfer, hoisting, installation guidance, and commissioning'
  '型号' = 'Model'
  '旋转阀' = 'Rotary valve'
  '旋转阀变频器' = 'Rotary valve VFD'
  '旋转阀厂家自配' = 'Supplied by rotary valve manufacturer'
  '压力变送器' = 'Pressure transmitter'
  '业主需要有机电操作维护能力人员，才能保持设备的最佳运转效率；' = 'The owner needs personnel with electromechanical operation and maintenance capability to maintain optimal equipment operating efficiency;'
  '一、原料给料系统' = 'I. Raw material feeding system'
  '以上报价不含电缆和桥架,不含缓存料仓、水气管路(由买方提供),不含管道保温。' = 'The above quotation does not include cables or trays, buffer silo, water and gas piping (to be provided by the buyer), or pipe insulation.'
  '以上报价不含任何涉及土建、设备和检修钢平台、建筑改动、拆墙、穿墙洞、打楼板等费用；' = 'The above quotation does not include any costs related to civil works, equipment and maintenance steel platforms, building modifications, wall demolition, wall openings, floor slab openings, etc.;'
  '以上报价含13%增值税，含现场指导安装调试费用，含运保费；' = 'The above quotation includes 13% VAT, on-site installation guidance and commissioning fees, and freight and insurance;'
  '运费、保险' = 'Freight and insurance'
  '真空上料器' = 'Vacuum conveyor'
  '振动变送器' = 'Vibration transmitter'
  '正泰电气元件，柜体材质：碳钢喷塑 仿威图；防护等级IP54' = 'CHINT electrical components, cabinet material: powder-coated carbon steel, Rittal-style; protection rating IP54'
  '郑州科航' = 'Zhengzhou Kehang'
  '支撑钢架' = 'Support steel frame'
  '指导安装调试费' = 'Installation guidance and commissioning fee'
  '主机' = 'Main unit'
  '主机变频器' = 'Main unit VFD'
  '主机电机' = 'Main unit motor'
  '主机轴承使用' = 'Main unit bearing application'
  '主机转速' = 'Main unit speed'
  '铸钢' = 'Cast steel'
  '转速变送器' = 'Speed transmitter'
  '转子' = 'Rotor'
  '转子碟片' = 'Rotor disc'
  '总  计：' = 'Total:'
  '总价' = 'Total Price'
  'C6高精度传感器(含仪表)' = 'C6 high-precision sensor (including instrument)'
  'DCM1500标配管，材质：304 表面不处理' = 'DCM1500 standard pipe, material: 304, untreated surface'
  'DCM1500标配管，材质：Q235 内表面喷防锈底漆，外表面喷底漆+面漆' = 'DCM1500 standard pipe, material: Q235, inner surface with anti-rust primer, outer surface with primer + topcoat'
  'DCM1500标配管，材质：S304 表面不处理' = 'DCM1500 standard pipe, material: S304, untreated surface'
  'DCM1500FJ碟巢磨改性系统' = 'DCM1500FJ disc-nest mill modification system'
  '配置报价表' = 'Configuration Quotation Sheet'
  "DCM1500FJ碟巢磨改性系统`n配置报价表" = "DCM1500FJ Disc-Nest Mill Modification System`nConfiguration Quotation Sheet"
  'PLC控制柜' = 'PLC control cabinet'
  'Q235  t=3.0 内表面除渣，外表面喷底漆+面漆' = 'Q235 t=3.0, inner surface deslagged, outer surface with primer + topcoat'
  'Q235+表面喷漆' = 'Q235 + painted surface'
  'Q785 表面喷涂碳化钨' = 'Q785 surface sprayed with tungsten carbide'
  'Q785 表面喷涂碳化钨,7层' = 'Q785 surface sprayed with tungsten carbide, 7 layers'
  'S304 1500L，含高低料位计' = 'S304 1500L, including high and low level gauges'
}

$excel = New-Object -ComObject Excel.Application
$excel.Visible = $false
$excel.DisplayAlerts = $false

try {
  $workbook = $excel.Workbooks.Open($sourcePath)

  foreach ($worksheet in $workbook.Worksheets) {
    if ($sheetNameMap.ContainsKey($worksheet.Name)) {
      $worksheet.Name = $sheetNameMap[$worksheet.Name]
    }

    $usedRange = $worksheet.UsedRange
    $rowCount = $usedRange.Rows.Count
    $columnCount = $usedRange.Columns.Count

    for ($row = 1; $row -le $rowCount; $row++) {
      for ($column = 1; $column -le $columnCount; $column++) {
        $cell = $usedRange.Cells.Item($row, $column)
        $value = $cell.Value2
        if ($value -is [string]) {
          $trimmed = $value.Trim()
          if ($translations.ContainsKey($trimmed)) {
            $leading = $value.Substring(0, $value.Length - $value.TrimStart().Length)
            $trailing = $value.Substring($value.TrimEnd().Length)
            $cell.Value2 = $leading + $translations[$trimmed] + $trailing
          }
        }
      }
    }
  }

  $workbook.SaveAs($outputPath, 51)
  $workbook.Close($true)
}
finally {
  if ($workbook) {
    [System.Runtime.Interopservices.Marshal]::ReleaseComObject($workbook) | Out-Null
  }
  $excel.Quit()
  [System.Runtime.Interopservices.Marshal]::ReleaseComObject($excel) | Out-Null
  [GC]::Collect()
  [GC]::WaitForPendingFinalizers()
}

Write-Output $outputPath
